---
abstract: 'parse ACNS messages and extract info into custom fields'
author:
  - 'Ruslan Zakirov <ruz@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-ACNS
no_index:
  directory:
    - etc
    - inc
    - t
requires:
  Parse::ACNS: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
